spring.application.name=auth-service

server.port=8080
spring.data.mongodb.uri=mongodb+srv://rajeevranjanprasad750:Ibm1234%40%23%24@auth-ms-db.vy28ujd.mongodb.net/auth_db?retryWrites=true&w=majority&appName=auth-ms-db
jwt.secret=YourVeryLongSecretKeyThatMustBeAtLeast32CharactersLong123456
jwt.expiration=86400000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packagesToScan=com.ibm.auth
