spring.application.name=auth-service

server.port=8081

spring.data.mongodb.uri=mongodb+srv://rajeevranjanprasad750:Ibm1234%40%23$@auth-ms-db.vy28ujd.mongodb.net/auth_db?retryWrites=true&w=majority&appName=auth-ms-db
