spring.application.name=auth-service

server.port=8080
spring.data.mongodb.uri=mongodb+srv://rajeevranjanprasad750:Ibm1234%40%23%24@auth-ms-db.vy28ujd.mongodb.net/auth_db?retryWrites=true&w=majority&appName=auth-ms-db
jwt.secret=YourVeryLongSecretKeyThatMustBeAtLeast32CharactersLong123456
jwt.expiration=86400000
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.packagesToScan=com.ibm.auth

#smtp
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=packagingwalainc@gmail.com
spring.mail.password=vzbfaklsmbnfkcio
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from=packagingwalainc@gmail.com